import "./globals.css";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";

import { auth } from "@/auth";
import SessionProvider from "@/components/SessionProvider";
import { Navbar } from "@/modules/navigation/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full"
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased mx-8 lg:mx-16 h-screen `}
      >
        <SessionProvider session={null}>{children}</SessionProvider>
        <Toaster />
      </body>
    </html>
  );
}
